name: CI

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Run tests
        run: pytest

  docker:
    needs: tests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
      DEFAULT_IMAGE_NAME: calof/job_worker_agent
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: |
          IMAGE="${IMAGE_NAME:-$DEFAULT_IMAGE_NAME}"
          docker build -t ${IMAGE}:${{ github.sha }} .
          echo "IMAGE=${IMAGE}" >> "$GITHUB_ENV"
      - name: Push image
        run: |
          IMAGE="${IMAGE_NAME:-$DEFAULT_IMAGE_NAME}"
          docker push ${IMAGE}:${{ github.sha }}
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker tag ${IMAGE}:${{ github.sha }} ${IMAGE}:latest
            docker push ${IMAGE}:latest
          fi
